set -e
true
true
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-hammer /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/corrected/configs/config.info
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/compress_all.py --input_file /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/corrected/corrected.yaml --ext_python_modules_home /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades --max_threads 8 --output_dir /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/corrected --gzip_output
true
true
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K21/configs/config.info
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K45/configs/config.info
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K65/configs/config.info
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K85/configs/config.info
/sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/bin/spades-core /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/configs/config.info
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/copy_files.py /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/before_rr.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/before_rr.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/assembly_graph_after_simplification.gfa /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/assembly_graph_after_simplification.gfa /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/final_contigs.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/contigs.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/first_pe_contigs.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/first_pe_contigs.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/strain_graph.gfa /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/strain_graph.gfa /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/scaffolds.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/scaffolds.fasta /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/scaffolds.paths /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/scaffolds.paths /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/assembly_graph_with_scaffolds.gfa /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/assembly_graph_with_scaffolds.gfa /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/assembly_graph.fastg /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/assembly_graph.fastg /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/K105/final_contigs.paths /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/contigs.paths
true
/sw/arch/eb/software/Python/3.12.3-GCCcore-13.3.0/bin/python3 /sw/arch/eb/software/SPAdes/4.2.0-GCC-13.3.0/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/scaffolds.fasta --misc_dir /gorilla/home/calle30/genome-analysis-moss/analyses/09_organelle/chloroplast/extended_spades/misc --threshold_for_breaking_scaffolds 3
true
